name: Reusable Python Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: true
        type: string
      run_command:
        description: 'Command to run the Python project'
        required: true
        type: string
    secrets:
      token:
        required: false  # Only needed for private repo access

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pytest

      - name: Install ngrok
        run: |
         curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
         echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
         sudo apt update && sudo apt install ngrok

      - name: Start Flask with ngrok
        run: |
         ngrok config add-authtoken 2ugRhrxf2KKivmZEE7mqbuSWO7f_4dwCNAdmSQ5UM5gHsdU2e
         ngrok http 5000 > /dev/null &
         sleep 5
         curl -s http://127.0.0.1:4040/api/tunnels  # Get the public URL


      - name: Run Python Project
        run: |
          ${{ inputs.run_command }}

