name: Trigger Repo-1 Test Workflow

on:
  push:
    branches:
      - main

jobs:
  call-repo-1-workflow:
    uses: ankitagrawal10/test-1/.github/workflows/reuseable.yml@master 
    with:
      python_version: '3.12'

  display-test-results:
    runs-on: self-hosted
    needs: call-repo-1-workflow  

    steps:
      # Check Python and Flask versions
      - name: Display Python and Flask versions
        run: |
          python --version
          flask --version

      # Step to run Flask app in the background
      - name: Run Flask App in the background
        run: |
          nohup python app.py &  # Run the Flask app in background
          sleep 5  # Give it time to start

      # Step to verify the Flask app is running (replace with actual test URL)
      - name: Check if Flask app is running
        run: |
          curl http://127.0.0.1:5000/  # Test the homepage (change URL if needed)
          curl http://127.0.0.1:5000/fetch  # If you have a fetch route or another URL to test
