name: Project-1 Workflow

on:
  push:
    branches:
      - master

jobs:
  use-reusable-pipeline:
    uses: ankitagrawal10/test-1/.github/workflows/reuseable.yml@master
    with:
      python_version: '3.12'
      # run_command: 'python app.py' 

  run-code:
    runs-on: self-hosted
    needs: use-reusable-pipeline
    steps:
      - name: Run python code
        run: | 
         echo -e "https://www.google.com" | python app.py
      # eof_input: 'https://www.google.com' 
