# .github/workflows/testing.yml in Repo-2
name: Trigger Repo-1 Test Workflow

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  call-repo-1-workflow:
    uses: ankitagrawal10/test-1/.github/workflows/reuseable.yml@master 
    with:
      python_version: '3.12'

  display-test-results:
    runs-on: self-hosted
    needs: call-repo-1-workflow  

    steps:
      - name: Display test results from pytest
        run: |
          python app.py  
