name: Project-1 Workflow

on:
  push:
    branches:
      - prod

jobs:
  use-reusable-pipeline:
    uses: ankitagrawal10/test-1/.github/workflows/reuseable.yml@master
    with:
      python_version: '3.12'
      run_command: 'echo -e "5\n10" | python app.py' 
     
