name: Project-1 Workflow

on:
  push:
    branches:
      - master

jobs:
  use-reusable-pipeline:
    uses: ankitagrawal10/test-1/.github/workflows/reusable-pipeline.yml@master
    with:
      python_version: '3.12'
      run_command: 'python app.py' 
